[google_sheets]
spreadsheet_id = "1LtMzKNZc16C07y1OEW2qmy-ai7sM-NIeKcGzZwdknyk"
credentials_path = "/run/secrets/google_creds"
worksheets = ["Cash", "Bond", "Crypto", "Gold", "Stock"]

[database]
host = "postgres"
port = 5432
name = "finance_db"